version: "3"
services:
  jupyter:
    build: .
    container_name: "jupyter"
    ports:
      - 8888:8888
    tty: true
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - C:\work\Python:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.token=''
